// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTlvuSzHXdplQEUxbYXlDkeM7CWJppJPE',
    appId: '1:958800443208:web:1fdcb6c4a4fcd58d7da57d',
    messagingSenderId: '958800443208',
    projectId: 'pbl-cnpm',
    authDomain: 'pbl-cnpm.firebaseapp.com',
    storageBucket: 'pbl-cnpm.firebasestorage.app',
    measurementId: 'G-EFBK396MX5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsygRc5DbK_h99rIWrCTxJqZV52Zoiv_E',
    appId: '1:958800443208:android:fdbda9b461089e287da57d',
    messagingSenderId: '958800443208',
    projectId: 'pbl-cnpm',
    storageBucket: 'pbl-cnpm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdG4cdjb-qHyBqhVMlA6NWhIfeTTQOH3g',
    appId: '1:958800443208:ios:5ca544ebd54074957da57d',
    messagingSenderId: '958800443208',
    projectId: 'pbl-cnpm',
    storageBucket: 'pbl-cnpm.firebasestorage.app',
    androidClientId: '958800443208-ijr2eba1kjh7p588nnedrv0vgm64n0df.apps.googleusercontent.com',
    iosClientId: '958800443208-ooubhp02bris17mgd5kqerarse005q10.apps.googleusercontent.com',
    iosBundleId: 'com.example.moneyboys',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdG4cdjb-qHyBqhVMlA6NWhIfeTTQOH3g',
    appId: '1:958800443208:ios:5ca544ebd54074957da57d',
    messagingSenderId: '958800443208',
    projectId: 'pbl-cnpm',
    storageBucket: 'pbl-cnpm.firebasestorage.app',
    androidClientId: '958800443208-ijr2eba1kjh7p588nnedrv0vgm64n0df.apps.googleusercontent.com',
    iosClientId: '958800443208-ooubhp02bris17mgd5kqerarse005q10.apps.googleusercontent.com',
    iosBundleId: 'com.example.moneyboys',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTlvuSzHXdplQEUxbYXlDkeM7CWJppJPE',
    appId: '1:958800443208:web:cbc808bf5fa80c807da57d',
    messagingSenderId: '958800443208',
    projectId: 'pbl-cnpm',
    authDomain: 'pbl-cnpm.firebaseapp.com',
    storageBucket: 'pbl-cnpm.firebasestorage.app',
    measurementId: 'G-5M0X7XT8PR',
  );
}
